### ISSUE TITLE
Too many bullets

### ISSUE THREAD

**Issue by ferndot** [corentin-R/ISS#1]
When I play this game on my Firefox OS-powered Flame, the game seems to create a bullet for each touch event. After a short period of time, the numerous bullets cause a significant decrease in the game's performance.

I recommend that you wait for some interval before creating each bullet.

**Comment by corentin-R** [comment]
Yeah, on Firefox for Android too, I think it comes from the timer method, I will try to change or improve it, thank you for the tip

**Comment by corentin-R** [comment]
Ok, this bug was fixed and a release was pushed on version 0.1.2 on the Mozilla Marketplace. But the game still suffers of slowdowns on some devices, I will try to fix that.

**Comment by ferndot** [comment]
Wonderful, thanks!
